---
# tasks file for create_ec2_keypair
- name: Creating a Key Pair
  ec2_key: 
    name: "new_key_pair"
    aws_access_key: "{{ lookup('env','aws_access_key') }}"
    aws_secret_key: "{{ lookup('env','aws_secret_key') }}"
    region: "us-east-1"
  register: ec2_key

- name: save private key
  copy:
    content: "{{ ec2_key.key.private_key }}" 
    dest: "./aws-private.pem" 
    mode: 0600
  when: ec2_key.changed