---
# tasks file for create_vpc
- name: Create new VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    state: present
    cidr_block: 172.23.0.0/16
    region: "{{ aws_region }}"
  register: vpc_register

# - name: Get VPC info
#   ec2_vpc_net_facts:
#     filters:
#       "tag:Name": "{{ vpc_name }}"
#     region: "{{ aws_region }}"
#   register: vpc_facts

- name: Getting Facts
  ec2_vpc_subnet_facts:
    filters:
      "tag:Name": "{{ vpc_name }}"
    region: "{{ aws_region }}"
  register: vpc_facts

## Need to get vpc_subnet_id from this output