---
# tasks file for create_vpc
- name: Create new VPC
  ec2_vpc_net:
    name: my_new_vpc
    state: present
    cidr_block: 172.23.0.0/16
    region: us-east-1
  register: vpc_register

- name: Set Facts
  set_fact: 
    some_fact = vpc_register

# - name: Get VPC info
#   ec2_vpc_subnet_info:
#     filters:
#       vpc-id: vpc_register.vpc

## Need to get vpc_subnet_id from this output