---
- name: Create s3 bucket
  s3_bucket:
    name: "mys3bucketakashbalani6895"
    region: "us-east-1"
    versioning: yes
    aws_access_key: "{{ lookup('env','aws_access_key') }}"
    aws_secret_key: "{{ lookup('env','aws_secret_key') }}"
  register: s3_url

- name: Display s3 url
  debug: var=s3_url